export const recipes = [
  {
    id: 1,
    backgroundImage: "/images/noodle.jpg",
    foodName: "Thang Noodle",
    cookingTime: 20,
    noOfServings: 4,
  },
  {
    id: 2,
    backgroundImage: "/images/cornSalad.jpg",
    foodName: "Corn Salad",
    cookingTime: 10,
    noOfServings: 2,
  },
  {
    id: 3,
    backgroundImage: "/images/mongoStickyRice.jpg",
    foodName: "Mongo Sticky Rice",
    cookingTime: 5,
    noOfServings: 1,
  },
  {
    id: 4,
    backgroundImage: "/images/noodle.jpg",
    foodName: "Thang Noodle",
    cookingTime: 20,
    noOfServings: 4,
  },
  {
    id: 5,
    backgroundImage: "/images/cornSalad.jpg",
    foodName: "Corn Salad",
    cookingTime: 10,
    noOfServings: 2,
  },
  {
    id: 6,
    backgroundImage: "/images/mongoStickyRice.jpg",
    foodName: "Mongo Sticky Rice",
    cookingTime: 5,
    noOfServings: 1,
  },
  {
    id: 7,
    backgroundImage: "/images/noodle.jpg",
    foodName: "Thang Noodle",
    cookingTime: 20,
    noOfServings: 4,
  },
  {
    id: 8,
    backgroundImage: "/images/cornSalad.jpg",
    foodName: "Corn Salad",
    cookingTime: 10,
    noOfServings: 2,
  },
  {
    id: 9,
    backgroundImage: "/images/mongoStickyRice.jpg",
    foodName: "Mongo Sticky Rice",
    cookingTime: 5,
    noOfServings: 1,
  },
];
